"""Embeds the dashboard's static assets (index.html, dashboard.html, job.html, *.js, *.css) into `static_bundle.py`.

Why: `modal.Image.add_local_python_source("abtract")` only ships `.py` files, so inside a Modal container the
`static/` directory does not exist. `app.py` serves from `static/` when it is present (local dev) and falls back to
`static_bundle.FILES` otherwise. `refresh_if_stale()` runs when app.py is imported locally (e.g. by `modal deploy`),
so the bundle can never be out of date at deploy time; `scripts/bundle_dashboard.py` does the same on demand.
"""
from __future__ import annotations

import importlib
import sys
from pathlib import Path

STATIC_DIR = Path(__file__).parent / "static"
BUNDLE_PATH = Path(__file__).parent / "static_bundle.py"
ASSET_EXTS = {".html", ".js", ".css", ".svg", ".json", ".txt", ".ico", ".png", ".woff2"}


def collect(static_dir: Path = STATIC_DIR) -> dict[str, bytes]:
    if not static_dir.is_dir():
        return {}
    out: dict[str, bytes] = {}
    for p in sorted(static_dir.rglob("*")):
        if p.is_file() and p.suffix.lower() in ASSET_EXTS and not p.name.startswith("."):
            out[str(p.relative_to(static_dir)).replace("\\", "/")] = p.read_bytes()
    return out


def render_source(files: dict[str, bytes]) -> str:
    lines = [
        '"""GENERATED by abtract/dashboard/bundle.py - do not edit. Static assets for the dashboard, used when the',
        'static/ directory is not present in the container (Modal only ships .py files)."""',
        "from __future__ import annotations",
        "",
        "FILES: dict[str, bytes] = {",
    ]
    for name, data in files.items():
        try:
            text = data.decode("utf-8")
            lit = repr(text)
            lines.append(f"    {name!r}: {lit}.encode('utf-8'),")
        except UnicodeDecodeError:
            lines.append(f"    {name!r}: {data!r},")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def current_bundle() -> dict[str, bytes] | None:
    if not BUNDLE_PATH.exists():
        return None
    try:
        mod = importlib.import_module("abtract.dashboard.static_bundle")
        mod = importlib.reload(mod) if "abtract.dashboard.static_bundle" in sys.modules else mod
        return dict(mod.FILES)
    except Exception:  # noqa: BLE001
        return None


def refresh_if_stale(static_dir: Path = STATIC_DIR, quiet: bool = True) -> bool:
    """Rewrite static_bundle.py when the static dir exists and differs from the bundle. Returns True if written."""
    files = collect(static_dir)
    if not files:
        return False
    if current_bundle() == files:
        return False
    BUNDLE_PATH.write_text(render_source(files))
    if not quiet:
        print(f"wrote {BUNDLE_PATH} ({len(files)} files, {sum(len(v) for v in files.values())} bytes)")
    return True
